# WEB SCRAPING â€“ ASSIGNMENT 2

Ans:-1

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
from selenium.webdriver.common.by import By
import time

In [2]:
driver=webdriver.Chrome(r'C:\Users\Ravishankar\Documents\chromedriver.exe')

In [5]:
driver.get("https://www.naukri.com")

In [6]:
designation=driver.find_element(By.CLASS_NAME,"suggestor-input ")
designation.send_keys("Data Analyst")

In [7]:
location=driver.find_element(By.XPATH,"/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input")
location.send_keys("Bangalore")

In [8]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [11]:
#Scraping Job Title
Job_Title=[]

title_tags=driver.find_elements(By.XPATH,'//a[@class="title fw500 ellipsis"]')
for i in title_tags[0:10]:
    Job_Title.append(i.text)
    
Job_Title

['Data Analyst - CRM Platform',
 'Hiring For Data Analyst (DA)/ Team Lead (TL) -Clinical Data management',
 'Payroll Transformation Data Analyst',
 'Master Data Management Business Analyst',
 'Data Analytics and Interpretation Business Analyst',
 'Data Analyst',
 'Data Analyst',
 'Senior Data Analyst',
 'Senior Data Analyst',
 'Senior Data Analyst | Fortune500 Retail Company']

In [12]:
#Scraping Location
Location=[]

location_tags=driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi location"]')
for i in location_tags[0:10]:
    Location.append(i.text)
    
Location

['Bangalore/Bengaluru, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Ahmedabad',
 'Bangalore/Bengaluru, Kolkata, Hyderabad/Secunderabad, Pune, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [13]:
#Scraping Company Name
Company_Name=[]

company_tags=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    Company_Name.append(i.text)
    
Company_Name

['Artech infosystem',
 'Cognizant',
 'Arrow Electronics',
 'Accenture',
 'Accenture',
 'ANZ',
 'ANZ',
 'Goalreify Ventures',
 'Goalreify Ventures',
 'Talent500']

In [14]:
#Scrapin Experience
Exp_Req=[]

Experience_tags=driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi experience"]')
for i in Experience_tags[0:10]:
    Exp_Req.append(i.text)
    
Exp_Req

['1-6 Yrs',
 '3-8 Yrs',
 '5-10 Yrs',
 '6-8 Yrs',
 '6-8 Yrs',
 '7-12 Yrs',
 '7-12 Yrs',
 '3-6 Yrs',
 '4-6 Yrs',
 '3-8 Yrs']

In [15]:
df=pd.DataFrame({'Job_Title':Job_Title,'Job_location':Location,'Company_Name':Company_Name,'Experience_Required':Exp_Req})
df

,Job_Title,Job_location,Company_Name,Experience_Required
0,Data Analyst - CRM Platform,"Bangalore/Bengaluru, Mumbai, Hyderabad/Secunde...",Artech infosystem,1-6 Yrs
1,Hiring For Data Analyst (DA)/ Team Lead (TL) -...,"Bangalore/Bengaluru, Kolkata, Hyderabad/Secund...",Cognizant,3-8 Yrs
2,Payroll Transformation Data Analyst,Bangalore/Bengaluru,Arrow Electronics,5-10 Yrs
3,Master Data Management Business Analyst,Bangalore/Bengaluru,Accenture,6-8 Yrs
4,Data Analytics and Interpretation Business Ana...,Bangalore/Bengaluru,Accenture,6-8 Yrs
5,Data Analyst,Bangalore/Bengaluru,ANZ,7-12 Yrs
6,Data Analyst,Bangalore/Bengaluru,ANZ,7-12 Yrs
7,Senior Data Analyst,Bangalore/Bengaluru,Goalreify Ventures,3-6 Yrs
8,Senior Data Analyst,Bangalore/Bengaluru,Goalreify Ventures,4-6 Yrs
9,Senior Data Analyst | Fortune500 Retail Company,Bangalore/Bengaluru,Talent500,3-8 Yrs

Ans:-2

In [55]:
driver.get('https://www.naukri.com')

In [56]:
designation=driver.find_element(By.CLASS_NAME,'suggestor-input')
designation.send_keys('Data Scientist')

In [57]:
location=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input')
location.send_keys('Bangalore')

In [9]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[6]')
search.click()

In [14]:
#Scraping Job Title
Job_Title=[]

job_tags=driver.find_elements(By.XPATH,'//a[@class="title fw500 ellipsis"]')
for i in job_tags[0:10]:
    Job_Title.append(i.text)
    
Job_Title

['Data Science Specialist',
 'Data Science Manager',
 'Mongodb Database Administrator, Maria DB or Cassandra',
 'Analystics & Modeling Specialist',
 'Assistant Manager - Data Science',
 'Data Scientist',
 'Senior Data Scientist',
 'Module Lead - BIDW',
 'Data Scientist: Artificial Intelligence',
 'ACN - Applied Intelligence - C4DI - Sustainability - 09']

In [15]:
#scrapin Job location
Job_Location=[]

loc=driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi location"]')
for i in loc[0:10]:
    Job_Location.append(i.text)
    
Job_Location

['Bangalore/Bengaluru, Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai',
 'Bangalore/Bengaluru, Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai',
 'Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune, Chennai, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru, Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, delhi ncr',
 'Bangalore/Bengaluru, Mumbai, Pune',
 'Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune, Chennai',
 'Bangalore/Bengaluru, Mumbai, New Delhi, Chennai',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [16]:
#scraping Company Name

Company_Name=[]

Name=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in Name[0:10]:
    Company_Name.append(i.text)
    
Company_Name

['Accenture',
 'Accenture',
 'Mphasis',
 'Accenture',
 'CitiusTech',
 'Tech Mahindra',
 'Boston Consulting Group',
 'Mphasis',
 'IBM',
 'Accenture']

In [17]:
df=pd.DataFrame({'Job-Title':Job_Title,'Job-Location':Job_Location,'Company-Name':Company_Name})
df

,Job-Title,Job-Location,Company-Name
0,Data Science Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture
1,Data Science Manager,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture
2,"Mongodb Database Administrator, Maria DB or Ca...","Bangalore/Bengaluru, Hyderabad/Secunderabad, P...",Mphasis
3,Analystics & Modeling Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture
4,Assistant Manager - Data Science,"Bangalore/Bengaluru, Mumbai, Pune",CitiusTech
5,Data Scientist,"Bangalore/Bengaluru, Hyderabad/Secunderabad, P...",Tech Mahindra
6,Senior Data Scientist,"Bangalore/Bengaluru, Mumbai, New Delhi, Chennai",Boston Consulting Group
7,Module Lead - BIDW,Bangalore/Bengaluru,Mphasis
8,Data Scientist: Artificial Intelligence,Bangalore/Bengaluru,IBM
9,ACN - Applied Intelligence - C4DI - Sustainabi...,Bangalore/Bengaluru,Accenture

Ans:-3

In [63]:
driver.get('https://www.naukri.com')

In [64]:
designation=driver.find_element(By.CLASS_NAME,'suggestor-input')
designation.send_keys('Data Scientist')

In [65]:
search=driver.find_element(By.CLASS_NAME,'qsbSubmit')
search.click()

In [66]:
#Applying Location(DElhi/NCR) filter
check=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/section[1]/div[2]/div[5]/div[2]/div[3]')
check.click()

In [67]:
#Applying Salary(3-6Lakhs) filter
check=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/section[1]/div[2]/div[6]/div[2]/div[2]')
check.click()

In [68]:
#scraping Job Title
Job_Title=[]
name=driver.find_elements(By.XPATH,'//a[@class="title fw500 ellipsis"]')
for i in name[0:10]:
    Job_Title.append(i.text)
    
#Scraping Job location
Job_Location=[]
loc=driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi location"]')
for i in loc[0:10]:
    Job_Location.append(i.text)
    
#Scraping Company Name
Company_Name=[]
cname=driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in cname[0:10]:
    Company_Name.append(i.text)

In [70]:
df=pd.DataFrame({'Job-Title':Job_Title,'Job-Location':Job_Location,'Company-Name':Company_Name})
df

,Job-Title,Job-Location,Company-Name
0,Data Scientist,"Noida, Nagpur, Bangalore/Bengaluru",GlobalLogic
1,DigitalBCG GAMMA Data Scientist,"New Delhi, Bangalore/Bengaluru",Boston Consulting Group
2,Lead Data Scientist,Noida(Sector-59 Noida)\n(WFH during Covid),R Systems International
3,Data Scientist,Gurgaon/Gurugram,IHS Markit
4,Data Scientist - Engine Algorithm,"Delhi / NCR, Kolkata, Mumbai, Hyderabad/Secund...",Primo Hiring
5,Data Scientist,Gurgaon/Gurugram,Optum
6,Data Scientist / Chat-bot Developer,"New Delhi, Bangalore/Bengaluru, Mumbai (All Ar...",Big Seo Buzz
7,Data Activation Specialist - Adobe Target,"Delhi / NCR, Kolkata, Mumbai, Hyderabad/Secund...",Okda Solutions
8,Data Scientist,Noida,NGI Ventures
9,Data Scientist,"Dehradun, Hyderabad/Secunderabad, Gurgaon/Guru...",torcai digital media

Ans:-4

In [64]:
driver.get('https://www.flipkart.com')

In [65]:
product=driver.find_element(By.CLASS_NAME,'_3704LK')
product.send_keys('sunglasses')

In [66]:
search=driver.find_element(By.CLASS_NAME,'L0Z3Pu')
search.click()

In [67]:
#Scraping Brand
Brand=[]
name=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
for i in name:
    Brand.append(i.text)
Brand

['FOSSIL',
 'FOSSIL',
 'Fastrack',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'SHAAH COLLECTIONS',
 'NuVew',
 'FOSSIL',
 'Bedst',
 'SHAAH COLLECTIONS',
 'MODE',
 'FOSSIL',
 'SHAAH COLLECTIONS',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'OAKLEY',
 'NuVew',
 'Fastrack',
 'NuVew',
 'OAKLEY',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'OAKLEY',
 'Mi',
 'Fastrack',
 'Fastrack',
 'OAKLEY',
 'SUNBEE',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'OAKLEY',
 'PIRASO',
 'SHAAH COLLECTIONS',
 'PIRASO',
 'OAKLEY',
 'Fastrack',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India']

In [68]:
#scraping Product Description
Product_Des=[]
pd=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
for i in pd:
    Product_Des.append(i.text)
Product_Des

['Others Rectangular Sunglasses (54)',
 'Others Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (57)',
 'Others Aviator Sunglasses (61)',
 'Others Round Sunglasses (59)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Others Round Sunglasses (50)',
 'UV Protection, Mirrored Wayfarer Sunglasses (54)',
 'UV Protection, Mirrored Wayfarer Sunglasses (54)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Rectangular Sunglass',
 'UV Protection, Mirrored Wayfarer Sunglasses (57)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (57)',
 'Shield Sunglass',
 'UV Protection Aviator Sunglasses (54)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'Rectangular Sunglass',
 'Polarized Aviator Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Shield Sunglasses (Free Size)',
 'Pitchman R Round Sunglass',
 'UV Protection, Polarized Wayfarer Sunglasses (Free Size...',
 'UV Protection Round Sunglasses (52)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'Retro Square Sunglass',
 'UV Protection Rectangular Sunglasses (52)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'Rectangular Sunglass',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Polarized, UV Protection Aviator Sunglasses (58)',
 'Polarized, UV Protection Wayfarer, Retro Square Sunglas...',
 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...']

In [69]:
#scraping price
Price=[]
price=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
for i in price:
    Price.append(i.text)
Price

['â‚¹2,279',
 'â‚¹2,899',
 'â‚¹499',
 'â‚¹79',
 'â‚¹449',
 'â‚¹79',
 'â‚¹100',
 'â‚¹2,909',
 'â‚¹79',
 'â‚¹79',
 'â‚¹79',
 'â‚¹2,199',
 'â‚¹79',
 'â‚¹79',
 'â‚¹499',
 'â‚¹7,799',
 'â‚¹74',
 'â‚¹809',
 'â‚¹79',
 'â‚¹6,449',
 'â‚¹167',
 'â‚¹375',
 'â‚¹459',
 'â‚¹10,929',
 'â‚¹499',
 'â‚¹479',
 'â‚¹529',
 'â‚¹6,889',
 'â‚¹214',
 'â‚¹79',
 'â‚¹359',
 'â‚¹5,139',
 'â‚¹184',
 'â‚¹79',
 'â‚¹244',
 'â‚¹5,979',
 'â‚¹459',
 'â‚¹461',
 'â‚¹424',
 'â‚¹507']

In [70]:
Brand_name=[]

In [71]:
#scraping Brand from next page
start=1
end=3
for page in range(start,end):
    brand=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in brand:
        Brand_name.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(3)

In [78]:
Brand_name

['FOSSIL',
 'FOSSIL',
 'Fastrack',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'SHAAH COLLECTIONS',
 'NuVew',
 'FOSSIL',
 'Bedst',
 'SHAAH COLLECTIONS',
 'MODE',
 'FOSSIL',
 'SHAAH COLLECTIONS',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'OAKLEY',
 'NuVew',
 'Fastrack',
 'NuVew',
 'OAKLEY',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'OAKLEY',
 'Mi',
 'Fastrack',
 'Fastrack',
 'OAKLEY',
 'SUNBEE',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'OAKLEY',
 'PIRASO',
 'SHAAH COLLECTIONS',
 'PIRASO',
 'OAKLEY',
 'Fastrack',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'IDEE',
 'New Specs',
 'Fastrack',
 'FOSSIL',
 'Sewell',
 'LIZA ANGEL',
 'VINCENT CHASE',
 'ROZZETTA CRAFT',
 'SHAAH COLLECTIONS',
 'VINCENT CHASE',
 'Fastrack',
 'VINCENT CHASE',
 'DEIXELS',
 'Fastrack',
 'New Specs',
 'CARRERA',
 'shah collections',
 'Fastrack',
 'VINCENT CHASE',
 'CARRERA',
 'LIZA ANGEL',
 'Fastrack',
 'ROZZETTA CRAFT',
 'FOSSIL',
 'Fastrack',
 'SRPM',
 'NuVew',
 'ROZZETTA CRAFT',
 'ALIXERO',
 'PIRASO',
 'IDEE',
 'CARRERA',
 'IDEE',
 'ROYAL SON',
 'NuVew',
 'CARRERA',
 'ROYAL SON',
 'Fastrack',
 'Fastrack',
 'ROZZETTA CRAFT']

In [81]:
Product_Description=[]

In [82]:
#scraping product description from next page
start=1
end=3
for page in range(start,end):
    product_desc=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in product_desc:
        Product_Description.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(3)

In [83]:
Product_Description

['Others Round Sunglasses (53)',
 'Polarized Retro Square Sunglasses (53)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'Others Round Sunglasses (59)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'UV Protection, Mirrored Wayfarer Sunglasses (54)',
 'UV Protection, Mirrored Wayfarer Sunglasses (54)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Round Sunglasses (54)',
 'UV Protection, Mirrored Wayfarer Sunglasses (57)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (57)',
 'Others Oval Sunglasses (52)',
 'UV Protection Aviator Sunglasses (54)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'Polarized, UV Protection Round Sunglasses (50)',
 'Polarized Aviator Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Shield Sunglasses (Free Size)',
 'by Lenskart Polarized, UV Protection Cat-eye Sunglasses...',
 'UV Protection, Polarized Wayfarer Sunglasses (Free Size...',
 'UV Protection Round Sunglasses (52)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'Polarized, UV Protection Aviator Sunglasses (57)',
 'UV Protection Rectangular Sunglasses (52)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'Riding Glasses, UV Protection Clubmaster, Wayfarer Sung...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Polarized, UV Protection Aviator Sunglasses (58)',
 'Polarized, UV Protection Wayfarer, Retro Square Sunglas...',
 'by Lenskart Polarized, UV Protection Cat-eye Sunglasses...',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'Others Rectangular Sunglasses (54)',
 'Mirrored, Night Vision, UV Protection, Riding Glasses S...',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'by Lenskart Polarized, UV Protection Aviator Sunglasses...',
 'Others Aviator Sunglasses (58)',
 'UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'by Lenskart Polarized, UV Protection Cat-eye Sunglasses...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'Others Aviator Sunglasses (61)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Oval Sunglasses (Free Size)',
 'Others Retro Square Sunglasses (51)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'by Lenskart Polarized, UV Protection Wayfarer Sunglasse...',
 'Rectangular Sunglass',
 'Riding Glasses, Night Vision Spectacle Sunglasses (Fre...',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'Shield Sunglass',
 'UV Protection Oval Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (50)',
 'UV Protection, Mirrored Aviator Sunglasses (57)',
 'Rectangular Sunglass',
 'UV Protection, Riding Glasses Retro Square Sunglasses (...',
 'UV Protection Wayfarer Sunglasses (55)',
 'Gradient, UV Protection Aviator Sunglasses (58)',
 'Pitchman R Round Sunglass',
 'UV Protection Wayfarer Sunglasses (18)',
 'Mirrored Aviator Sunglasses (55)',
 'UV Protection Wayfarer Sunglasses (57)',
 'Retro Square Sunglass',
 'Polarized, UV Protection Wayfarer Sunglasses (61)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Shield Sunglasses (Free Size)',
 'Rectangular Sunglass']

In [86]:
Price1=[]

In [87]:
#scraping product description from next page
start=1
end=3
for page in range(start,end):
    price1=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in price1:
        Price1.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(3)

In [88]:
Price1

['â‚¹3,999',
 'â‚¹2,199',
 'â‚¹499',
 'â‚¹79',
 'â‚¹449',
 'â‚¹79',
 'â‚¹100',
 'â‚¹287',
 'â‚¹79',
 'â‚¹79',
 'â‚¹79',
 'â‚¹2,279',
 'â‚¹79',
 'â‚¹79',
 'â‚¹499',
 'â‚¹706',
 'â‚¹74',
 'â‚¹809',
 'â‚¹79',
 'â‚¹799',
 'â‚¹167',
 'â‚¹375',
 'â‚¹459',
 'â‚¹236',
 'â‚¹499',
 'â‚¹479',
 'â‚¹529',
 'â‚¹223',
 'â‚¹214',
 'â‚¹79',
 'â‚¹359',
 'â‚¹499',
 'â‚¹184',
 'â‚¹79',
 'â‚¹244',
 'â‚¹899',
 'â‚¹459',
 'â‚¹461',
 'â‚¹424',
 'â‚¹801',
 'â‚¹1,029',
 'â‚¹200',
 'â‚¹809',
 'â‚¹2,279',
 'â‚¹200',
 'â‚¹120',
 'â‚¹599',
 'â‚¹2,899',
 'â‚¹148',
 'â‚¹499',
 'â‚¹599',
 'â‚¹2,909',
 'â‚¹188',
 'â‚¹529',
 'â‚¹79',
 'â‚¹7,799',
 'â‚¹79',
 'â‚¹409',
 'â‚¹599',
 'â‚¹6,449',
 'â‚¹151',
 'â‚¹809',
 'â‚¹255',
 'â‚¹10,929',
 'â‚¹1,149',
 'â‚¹146',
 'â‚¹79',
 'â‚¹6,889',
 'â‚¹223',
 'â‚¹189',
 'â‚¹1,029',
 'â‚¹5,139',
 'â‚¹1,099',
 'â‚¹271',
 'â‚¹79',
 'â‚¹287',
 'â‚¹424',
 'â‚¹529',
 'â‚¹529',
 'â‚¹5,979']

Ans:-5

In [91]:
driver.get('https://www.flipkart.com')

In [92]:
product=driver.find_element(By.CLASS_NAME,'_3704LK')
product.send_keys('iphone 11')

In [93]:
search=driver.find_element(By.CLASS_NAME,'L0Z3Pu')
search.click()

In [94]:
clk=driver.find_element(By.XPATH,'//a[@class="_1fQZEK"]')
clk.click()

In [99]:
Rating=[]

In [102]:
#Scraping Rating
start=0
end=12
for page in range(start,end):
    rating=driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    for i in rating:
        Rating.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]') 
    nxt.click()
    time.sleep(3)

In [103]:
Rating

['5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5']

In [106]:
Review_sum=[]

In [107]:
#scraping Review Summary
start=0
end=12
for page in range(start,end):
    rev=driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    for i in rev:
        Review_sum.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]') 
    nxt.click()
    time.sleep(3)

In [108]:
Review_sum

['Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Perfect product!',
 'Terrific',
 'Value-for-money',
 'Classy product',
 'Good quality product',
 'Perfect product!',
 'Fabulous!',
 'Mind-blowing purchase']

In [110]:
Full_rev=[]

In [111]:
#scraping full review
start=0
end=12
for page in range(start,end):
    frev=driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]')
    for i in frev:
        Full_rev.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]') 
    nxt.click()
    time.sleep(3)

In [112]:
Full_rev

["After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.',
 "After using 3 years mobile review. Excellent & Awesome Mobile fully I love it mobile don't wait take it perfectly suits everyone very stylish and operating a...\nRead full review",
 'I am using the phone for last 5 years and found no cons as such. The camera quality is bit low as compared to other iphone varient but it can be managable. B...\nRead full review',
 "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.",
 'Awesome for this price range',
 "impressively Nice......\nOne of the greatest iPhone i ever used ....\nAll was like Never before ...\nit's just Amazing ...\nBattery Life is too good ...2 Days wi...\nRead full review",
 'Nice products thanks flkat',
 'Fast performance to previous iPhone x\nGood camera quality but the best part of night mode #killing\n\nI am already One-plus7\nHuge difference between in night m...\nRead full review',
 'Fantastic and prompt delivery.']

Ans:-6

In [3]:
driver.get('https://www.flipkart.com')

In [4]:
product=driver.find_element(By.CLASS_NAME,'_3704LK')
product.send_keys('sneakers')

In [5]:
search=driver.find_element(By.CLASS_NAME,'L0Z3Pu')
search.click()

In [6]:
Brand=[]

In [7]:
#scraping brand
start=0
end=3
for page in range(start,end):
    brand=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in brand:
        Brand.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')  
    nxt.click()
    time.sleep(3)

In [8]:
Brand

['Wildcraft',
 'TR',
 'RED TAPE',
 'BRUTON',
 'BRUTON',
 'World Wear Footwear',
 'RED TAPE',
 'Deals4you',
 'Labbin',
 'Magnolia',
 'World Wear Footwear',
 'BIRDE',
 'TR',
 'World Wear Footwear',
 'BRUTON',
 'BIRDE',
 'Kraasa',
 'PUMA',
 'Magnolia',
 'RapidBox',
 'World Wear Footwear',
 "K' Footlance",
 'Shozie',
 'Layasa',
 'Rzisbo',
 'SCATCHITE',
 'BRUTON',
 'bacca bucci',
 'aadi',
 'tigonis',
 'Magnolia',
 "'Trends'",
 'aadi',
 'ASTEROID',
 'Deals4you',
 'TR',
 'Robbie jones',
 'K- FOOTLANCE',
 'BRUTON',
 'PUMA',
 'BRUTON',
 'WHITE WALKERS',
 'BRUTON',
 'Wildcraft',
 'PUMA',
 'Sparx',
 'Elevarse',
 'TR',
 'aadi',
 'Shozie',
 'BRUTON',
 'asian',
 'Deals4you',
 "Neeman's",
 'asian',
 'BIRDE',
 'RapidBox',
 'World Wear Footwear',
 'K- FOOTLANCE',
 'BIRDE',
 'Kzaara',
 'BRUTON',
 'BRUTON',
 'Deals4you',
 'WOODLAND',
 'HIGHLANDER',
 'Layasa',
 'RapidBox',
 'Layasa',
 'HRX by Hrithik Roshan',
 'RED TAPE',
 'bacca bucci',
 'HIGHLANDER',
 'Shozie',
 'D-SNEAKERZ',
 "'Trends'",
 'Airland',
 'LANCER',
 'Chevit',
 'TR',
 'TR',
 'Layasa',
 'RED TAPE',
 'BRUTON',
 'BRUTON',
 'World Wear Footwear',
 'RED TAPE',
 'Xylus',
 'Labbin',
 'Magnolia',
 'World Wear Footwear',
 'BRUTON',
 'TR',
 'World Wear Footwear',
 'BRUTON',
 'BRUTON',
 'Kraasa',
 'PUMA',
 'Magnolia',
 'BRUTON',
 'World Wear Footwear',
 "K' Footlance",
 'Shozie',
 'HRX by Hrithik Roshan',
 'Rzisbo',
 'SCATCHITE',
 'BRUTON',
 'DUCATI',
 'aadi',
 'tigonis',
 'Magnolia',
 "'Trends'",
 'aadi',
 'ASTEROID',
 'Deals4you',
 'RED TAPE',
 'Robbie jones',
 'K- FOOTLANCE',
 'BRUTON',
 'U.S. POLO ASSN.']

In [10]:
Product_Desc=[]

In [13]:
#scraping product description
start=0
end=3
for page in range(start,end):
    pr=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in pr:
        Product_Desc.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')  
    nxt.click()
    time.sleep(3)

In [14]:
Product_Desc

['True Black Shoe Sneakers For Men',
 'Casual White Sneakers For Men',
 'Sneakers For Men',
 'Modern Trendy Sneakers Shoes Sneakers For Men',
 'Lightweight Pack Of 1 Trendy Sneakers Sneakers For Men',
 'Latest Collection-1215 Stylish Casual Sports Sneakers F...',
 'Sneakers For Men',
 "Newton-01 Men's Lightweight Running Shoes Sneakers For ...",
 'Sneakers For Men',
 'Sneakers For Men',
 'Latest Collection Black-349 Trendy & Stylish Casual Sne...',
 'Sneakers For Men',
 'Casual Sneakers For Men',
 'Latest Collection-1216 Stylish Casual Sports Sneakers F...',
 'Lattest Sneakers Shoe Sneakers For Men',
 "JUPITER Men's Retro Color Blocked Light Weight Chunky F...",
 'Casuals, Canvas, Partywear Sneakers For Men',
 'Electron E Pro Sneakers For Men',
 'Sneakers For Men',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Exclusive Affordable Collection of Trendy & Stylish Cas...',
 'Fashion and Stylish Soft Ultralight Lace Up Sneakers Ca...',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Modern Trendy Sneakers Shoes Sneakers For Men',
 'Rebound LayUp SL Sneakers For Men',
 'Sneakers For Men',
 'Tigonis Casuals For Men Sneakers For Men (White) Sneake...',
 'Sneakers For Men',
 'SM-734 Sneakers For Men',
 'Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Women',
 'STREET SAMURAI High top Flat high Street Fashion Sneake...',
 'Casual Sneakers Canvas Shoes For Men Sneakers For Men',
 'Sneakers For Men',
 'Sneaker Sneakers For Men',
 '2 Combo Sneaker Shoes Sneakers For Men',
 'Exclusive Sneaker Shoes Sneakers For Men',
 'Stylish & Trending Outdoor Walking Comfortable Sneakers...',
 '2 Combo Sneaker Shoes Sneakers For Men',
 'Premium Casual Shoes White Sneakers For Men',
 'RS-FAST GO FOR Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Premium White Casual Shoes Sneakers For Men Sneakers Fo...',
 'Mesh | Ultralightweight | Comfortable | Breathable Walk...',
 'Synthetic Leather Casual Sneaker shoes for Mens Sneaker...',
 '2 Combo Sneaker Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Women',
 'Sneakers For Men',
 'Skypy-31 Walking Shoes,Training Shoes,Sneakers,Loafers,...',
 "JUPITER Men's Retro Color Blocked Light Weight Chunky F...",
 'Sneakers For Men',
 'Latest Collection-1138 Stylish Casual Sports Sneakers F...',
 'Sneakers For Men',
 "Newton-01 Men's Lightweight Running Shoes Sneakers For ...",
 'Sneakers For Men',
 '2 Combo Sneaker Shoes Sneakers For Men',
 'Combo Pack Of 2 Latest Stylish Casual Shoes for Men Lac...',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Sneakers For Women',
 'Sneakers For Men',
 'Sneakers For Men',
 'Rebound LayUp SL Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'SM-734 Sneakers For Men',
 '350 smart grey lace-ups casual for men Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'SM-322 Sneakers For Men',
 'True Black Shoe Sneakers For Men',
 'Casual White Sneakers For Men',
 'Sneakers For Men',
 'Modern Trendy Sneakers Shoes Sneakers For Men',
 'Lightweight Pack Of 1 Trendy Sneakers Sneakers For Men',
 'Latest Collection-1215 Stylish Casual Sports Sneakers F...',
 'Sneakers For Men',
 'STREET SAMURAI High top Flat high Street Fashion Sneake...',
 'Sneakers For Men',
 'Sneakers For Men',
 'Latest Collection Black-349 Trendy & Stylish Casual Sne...',
 'Sneakers For Men',
 'Casual Sneakers For Men',
 'Latest Collection-1216 Stylish Casual Sports Sneakers F...',
 'Lattest Sneakers Shoe Sneakers For Men',
 'MADRYN 2.O Sneakers For Men',
 'Casuals, Canvas, Partywear Sneakers For Men',
 'Electron E Pro Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Exclusive Affordable Collection of Trendy & Stylish Cas...',
 'Fashion and Stylish Soft Ultralight Lace Up Sneakers Ca...',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Modern Trendy Sneakers Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Tigonis Casuals For Men Sneakers For Men (White) Sneake...',
 'Sneakers For Men',
 '2 Combo Sneaker Shoes Sneakers For Men',
 'Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Women',
 'DEMON High-top casual shoe with Flat outsole high Stree...',
 'Casual Sneakers Canvas Shoes For Men Sneakers For Men',
 'Sneakers For Men',
 'Sneaker Sneakers For Men',
 '2 Combo Sneaker Shoes Sneakers For Men']

In [16]:
Price=[]

In [17]:
#scraping price
start=0
end=3
for page in range(start,end):
    price=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in price:
        Price.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')  
    nxt.click()
    time.sleep(3)

In [18]:
Price

['â‚¹239',
 'â‚¹409',
 'â‚¹399',
 'â‚¹530',
 'â‚¹4,699',
 'â‚¹583',
 'â‚¹233',
 'â‚¹359',
 'â‚¹239',
 'â‚¹287',
 'â‚¹399',
 'â‚¹319',
 'â‚¹344',
 'â‚¹1,399',
 'â‚¹473',
 'â‚¹392',
 'â‚¹449',
 'â‚¹143',
 'â‚¹239',
 'â‚¹1,320',
 'â‚¹159',
 'â‚¹399',
 'â‚¹393',
 'â‚¹380',
 'â‚¹1,298',
 'â‚¹596',
 'â‚¹319',
 'â‚¹236',
 'â‚¹399',
 'â‚¹1,275',
 'â‚¹939',
 'â‚¹4,899',
 'â‚¹335',
 'â‚¹260',
 'â‚¹236',
 'â‚¹545',
 'â‚¹143',
 'â‚¹999',
 'â‚¹398',
 'â‚¹319',
 'â‚¹1,069',
 'â‚¹239',
 'â‚¹899',
 'â‚¹191',
 'â‚¹143',
 'â‚¹143',
 'â‚¹899',
 'â‚¹1,320',
 'â‚¹319',
 'â‚¹239',
 'â‚¹179',
 'â‚¹1,159',
 'â‚¹239',
 'â‚¹143',
 'â‚¹195',
 'â‚¹2,109',
 'â‚¹342',
 'â‚¹1,749',
 'â‚¹239',
 'â‚¹1,049',
 'â‚¹239',
 'â‚¹239',
 'â‚¹318',
 'â‚¹359',
 'â‚¹329',
 'â‚¹288',
 'â‚¹399',
 'â‚¹739',
 'â‚¹239',
 'â‚¹399',
 'â‚¹239',
 'â‚¹399',
 'â‚¹223',
 'â‚¹399',
 'â‚¹260',
 'â‚¹1,414',
 'â‚¹316',
 'â‚¹319',
 'â‚¹206',
 'â‚¹399',
 'â‚¹583',
 'â‚¹239',
 'â‚¹1,399',
 'â‚¹530',
 'â‚¹216',
 'â‚¹449',
 'â‚¹239',
 'â‚¹359',
 'â‚¹399',
 'â‚¹393',
 'â‚¹1,298',
 'â‚¹319',
 'â‚¹344',
 'â‚¹159',
 'â‚¹596',
 'â‚¹392',
 'â‚¹319',
 'â‚¹239',
 'â‚¹939',
 'â‚¹1,320',
 'â‚¹1,275',
 'â‚¹335',
 'â‚¹260',
 'â‚¹236',
 'â‚¹236',
 'â‚¹143',
 'â‚¹999',
 'â‚¹380',
 'â‚¹143',
 'â‚¹399',
 'â‚¹135',
 'â‚¹4,899',
 'â‚¹287',
 'â‚¹239',
 'â‚¹341',
 'â‚¹545',
 'â‚¹1,599',
 'â‚¹239',
 'â‚¹288',
 'â‚¹773']

In [20]:
Offer=[]

In [21]:
#scraping product description
start=0
end=3
for page in range(start,end):
    off=driver.find_elements(By.XPATH,'//div[@class="_3Ay6Sb"]')
    for i in off:
        Offer.append(i.text)
    nxt=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')  
    nxt.click()
    time.sleep(3)

In [22]:
Offer

['58% off',
 '84% off',
 '82% off',
 '85% off',
 '76% off',
 '71% off',
 '82% off',
 '62% off',
 '68% off',
 '76% off',
 '64% off',
 '37% off',
 '84% off',
 '71% off',
 '65% off',
 '68% off',
 '84% off',
 '65% off',
 '52% off',
 '64% off',
 '76% off',
 '76% off',
 '68% off',
 '82% off',
 '67% off',
 '69% off',
 '88% off',
 '74% off',
 '73% off',
 '76% off',
 '80% off',
 '47% off',
 '84% off',
 '81% off',
 '73% off',
 '84% off',
 '65% off',
 '84% off',
 '53% off',
 '77% off',
 '35% off',
 '88% off',
 '53% off',
 '75% off',
 '78% off',
 '55% off',
 '76% off',
 '76% off',
 '84% off',
 '84% off',
 '62% off',
 '78% off',
 '77% off',
 '84% off',
 '70% off',
 '60% off',
 '68% off',
 '81% off',
 '81% off',
 '60% off',
 '74% off',
 '72% off',
 '73% off',
 '84% off',
 '64% off',
 '71% off',
 '50% off',
 '61% off',
 '71% off',
 '60% off',
 '72% off',
 '2% off',
 '77% off',
 '76% off',
 '73% off',
 '78% off',
 '52% off',
 '76% off',
 '71% off',
 '67% off',
 '58% off',
 '84% off',
 '82% off',
 '85% off',
 '76% off',
 '71% off',
 '82% off',
 '54% off',
 '68% off',
 '76% off',
 '64% off',
 '64% off',
 '84% off',
 '71% off',
 '65% off',
 '74% off',
 '84% off',
 '65% off',
 '52% off',
 '84% off',
 '76% off',
 '76% off',
 '68% off',
 '84% off',
 '67% off',
 '69% off',
 '88% off',
 '64% off',
 '73% off',
 '76% off',
 '80% off',
 '82% off',
 '84% off',
 '81% off',
 '73% off',
 '84% off',
 '65% off',
 '84% off',
 '53% off',
 '78% off']

Ans:-7

In [26]:
driver.get('https://www.myntra.com/shoes')

In [27]:
#applying color filter
chk=driver.find_element(By.XPATH,'//li[@class="colour-listItem"]')
chk.click()

In [29]:
#applying price filter
ck=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label')
ck.click()

In [30]:
Brand=[]

In [31]:
#scraping Brand
start=0
end=2
for page in range(start,end):
    brand=driver.find_elements(By.XPATH,'//h3[@class="product-brand"]')
    for i in brand:
        Brand.append(i.text)
    nxt=driver.find_element(By.XPATH,'//li[@class="pagination-next"]')   
    nxt.click()
    time.sleep(3)

In [32]:
Brand

['Skechers',
 'Skechers',
 'Skechers',
 'ADIDAS',
 'Puma',
 'Skechers',
 'Puma',
 'Skechers',
 'Skechers',
 'Puma',
 'ADIDAS',
 'Nike',
 'ADIDAS Originals',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'ADIDAS',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'Puma',
 'Louis Philippe',
 'UNDER ARMOUR',
 'Puma',
 'ADIDAS',
 'Tommy Hilfiger',
 'ADIDAS',
 'Skechers',
 'UNDER ARMOUR',
 'Puma',
 'Puma',
 'Skechers',
 'ADIDAS',
 'ADIDAS',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Nike',
 'Nike',
 'PUMA Motorsport',
 'Skechers',
 'ADIDAS',
 'Puma',
 'Puma',
 'Puma',
 'ADIDAS',
 'Skechers',
 'ADIDAS Originals',
 'Skechers',
 'Puma',
 'Tommy Hilfiger',
 'ADIDAS Originals',
 'Skechers',
 'Skechers',
 'UNDER ARMOUR',
 'Reebok',
 'UNDER ARMOUR',
 'Calvin Klein',
 'Skechers',
 'Puma',
 'ADIDAS Originals',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Skechers',
 'ADIDAS',
 'Puma',
 'Hush Puppies',
 'Ruosh',
 'ADIDAS',
 'Xtep',
 'ADIDAS',
 'Skechers',
 'ADIDAS',
 'Tommy Hilfiger',
 'Louis Philippe',
 'Puma',
 'Saint G',
 'ADIDAS',
 'Tommy Hilfiger',
 'Skechers',
 'Calvin Klein',
 'Skechers',
 'ADIDAS',
 'Skechers',
 'Xtep',
 'Calvin Klein',
 'Hush Puppies',
 'FORCLAZ By Decathlon',
 'ADIDAS',
 'Tommy Hilfiger',
 'ALDO',
 'Tommy Hilfiger',
 'Skechers',
 'UNDER ARMOUR',
 'MANGO',
 'Skechers',
 'Hush Puppies',
 'Louis Philippe',
 'Skechers',
 'ADIDAS',
 'ROSSO BRUNELLO',
 'Louis Philippe']

In [34]:
Desc=[]

In [35]:
#scraping description
start=0
end=2
for page in range(start,end):
    des=driver.find_elements(By.XPATH,'//h4[@class="product-product"]')
    for i in des:
        Desc.append(i.text)
    nxt=driver.find_element(By.XPATH,'//li[@class="pagination-next"]')   
    nxt.click()
    time.sleep(3)

In [36]:
Desc

['Men Velocity Nitro 2 Running',
 'Men Solid Sneakers',
 'Men SPORTY RUNNER Sneakers',
 'Women GO WALK 4 - GIFTED Shoes',
 'Women Sports Shoes',
 'Men Leather Formal Brogues',
 'PEAKFREAK OUTDRY Trekking Shoe',
 'Women Flex Appeal 3.0 Sneakers',
 'Men Leather Formal Derbys',
 'Solid Formal Leather Monk Shoes',
 'Men Sneakers',
 'Men Textured Leather Slip-On Sneakers',
 'Men Leather Sneakers',
 'Men Leather Derbys',
 'Men Solid Lightweight Sneakers',
 'Men ALANINE Running Shoes',
 'Block Heeled Boots',
 'Men Running Shoes',
 'Men MAX ELITE Running Shoes',
 'SKECH-AIR EDGE BRITE Sneakers',
 'Leather High-Top Heeled Boots',
 'Leather Wedge Sandals',
 "Women D'LUX WALKER Sneakers",
 'Women Enlighten Shoes',
 'Embellished Flatform Sandals',
 'Men Running Shoes',
 'Men Leather Sneakers',
 'Women Velocity Nitro 2 Running',
 'Men Sports Shoes',
 'Men Leather Sneakers',
 'Women Electrify Nitro Running',
 'Men Suede Sneakers',
 'Men Solid Leather Formal Loafers',
 'Men Leather Formal Brogues',
 'W omen TriBase Reign 4 Running',
 'Men Solid Leather Formal Loafers',
 'Women REDMOND V2 TrekkingShoe',
 'Men Canvas Slip-On Sneakers',
 'Leather Ankle Boots',
 'Men Textured Leather Formal Loafers',
 'Embellished PU Comfort Pumps',
 'Men Skateboarding Shoes',
 'Women GO RUN FAST-DAZZLE Shoes',
 'Slim Heels',
 'Women T-Strap Flats',
 'Cascade Peak II Jacket',
 'Men Textured Leather Sneakers',
 'Men Woven Design Suede Flat Boots',
 'Men Solid Leather Formal Derbys',
 'Men Solid Formal Leather Slip-On Shoes',
 'Men Solid Leather Formal Slip-On',
 '',
 'Men Textured Leather Loafers',
 'Men Solid Leather Formal Loafers',
 'Men Black Leather Loafers',
 'Men Solid Leather Formal Slip-Ons',
 'Men Leather Fashion',
 'Men Textured Leather Loafers',
 'Textured Block Sandals',
 'Men Leather Derbys',
 'Men Textured Leather Formal Loafers',
 'Women Ballerinas Flats',
 'Men Leather Driving Shoes',
 'Men Woven Design Sneakers',
 'Men Perforations Leather Loafers',
 'Men Arch Fit Sneakers',
 'Men Textured Formal Leather Loafers',
 'Men Canvas Slip-On Sneakers',
 'Men Leather Loafers',
 'Men Leather Formal Derbys',
 'Embellished PU Party Block Peep Toes',
 'Embellished Chelsea Boots',
 'Women Rope Espadrille',
 'Embellished Block Pumps with Buckles',
 'Men Slip-On Sneakers',
 'Women Lace Espadrilles',
 'Men Sneakers',
 'Men Solid Leather Formal Monks',
 'Leather Block Pumps',
 'Men Solid Leather Formal Oxfords',
 'Men Woven Design Sneakers',
 'Men Solid Formal Leather Slip-On Shoes',
 'Men Textured Leather Formal Slip-Ons',
 'Men Slip-On Sneakers',
 'Leather Block Sandals with Buckles',
 'Women Block Heeled Boots',
 'Women Open Toe Flats',
 'Embellished Flatform Boots',
 'Embellished Leather Wedge Sandals',
 'Women Solid Chelsea Boots',
 'Women Block Heeled Boots',
 'Women Open Toe Flats',
 'Women Slip-On Sneakers',
 'Women Sunny Street Sneakers',
 'Leather Comfort Sandals',
 'Leather Block Heels',
 'Women Open Toe Flats',
 'Embellished PU Wedge Sandals',
 'PU Flatform Sandals',
 'GEL-Pulse 13 Running Shoes']

In [38]:
Price=[]

In [39]:
#scraping Price
start=0
end=2
for page in range(start,end):
    price=driver.find_elements(By.XPATH,'//span[@class="product-discountedPrice"]')
    for i in price:
        Price.append(i.text)
    nxt=driver.find_element(By.XPATH,'//li[@class="pagination-next"]')   
    nxt.click()
    time.sleep(3)

In [40]:
Price

['Rs. 8399',
 'Rs. 6019',
 'Rs. 11199',
 'Rs. 8799',
 'Rs. 5999',
 'Rs. 11192',
 'Rs. 8010',
 'Rs. 6300',
 'Rs. 6750',
 'Rs. 8999',
 'Rs. 8075',
 'Rs. 8320',
 'Rs. 7439',
 'Rs. 6750',
 'Rs. 8100',
 'Rs. 10199',
 'Rs. 8550',
 'Rs. 8550',
 'Rs. 7650',
 'Rs. 6999',
 'Rs. 9099',
 'Rs. 6599',
 'Rs. 8550',
 'Rs. 8550',
 'Rs. 9450',
 'Rs. 11250',
 'Rs. 6860',
 'Rs. 6860',
 'Rs. 7499',
 'Rs. 7499']

Ans:-8

In [3]:
driver.get('https://www.amazon.in')

In [4]:
product=driver.find_element(By.XPATH,'//input[@class="nav-input nav-progressive-attribute"]')
product.send_keys('Laptop')

In [5]:
search=driver.find_element(By.XPATH,'//div[@class="nav-search-submit nav-sprite"]')
search.click()

In [6]:
#applying cpu filter
chk=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[5]/li[11]/span/a/div/label/i')
chk.click()

In [7]:
#scraping title
Title=[]
title=driver.find_elements(By.XPATH,'//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')

for i in title[0:10]:
    Title.append(i.text)
    
Title

['ASUS Vivobook 15, 15.6-inch (39.62 cms) FHD, Intel Core i7-1065G7 10th Gen, Thin and Light Laptop (16GB/512GB SSD/Iris Plus Graphics/Windows 11/Office 2021/Silver/1.8 kg), X515JA-EJ701WS',
 'Hp Pavilion X360 11Th Gen Intel Core I7 14 Inches Fhd Multitouch 2In1 Laptop (16Gb Ram/512Gb Ssd/B&O/Windows 11 Home/Fpr/Backlit Kb/Intel Iris Xe Graphics/Pen/Alexa/Ms Office/Silver/1.52Kg)14-Dy1047Tu',
 'ASUS Zenbook 13 OLED, 13.3-inch (33.78 cms) FHD OLED, Intel EVO Core i7-1165G7 11th Gen, Thin and Light Laptop (16GB/1TB SSD/Iris Xe Graphics/Windows 11/Office 2021/Mist/1.14 kg), UX325EA-KG701WS',
 'Lenovo IdeaPad Slim 5 Intel Core i7 12th Gen 15.6" (39.62cm) FHD IPS Thin & Light Laptop (16GB/512GB SSD/Windows 11/Office 2021/Backlit/FPR/3months Game Pass/Storm Grey/1.85Kg), 82SF008WIN',
 'HP Pavilion x360 11th Gen Intel Core i7 14 inch(35.6 cm) FHD,IPS, Multitouch 2-in-1 Laptop(16GB RAM/512GB SSD/Backlit KB/Intel Iris Xe Graphics/Pen/Alexa Built-in/MSO/1.52Kg) 14-dy1050TU, Spruce Blue',
 'ASUS Vivobook 15, 15.6-inch (39.62 cms) FHD, Intel Core i7-1065G7 10th Gen, Thin and Light Laptop (16GB/512GB SSD/Iris Plus Graphics/Windows 11/Office 2021/Silver/1.8 kg), X515JA-EJ701WS',
 'Lenovo ThinkBook 15 Intel 11th Gen Core i7 15.6"(39.62 cm)FHD Thin and Light Laptop (16GB/512GB SSD/Windows 11 Home/MS Office H&S 2021/IrisÂ® Xe Graphics/Backlit/Mineral Grey/1.7 Kg) 20VE00W4IH',
 'HP Pavilion Plus, 12th Gen Intel Core i7 16GB RAM/1TB SSD 14 inch(35.6 cm),OLED,400 nits,UWVA, Eye Safe Laptop/Intel Iris Xe Graphics/Backlit KB/B&O/FPR/Win 11/Alexa Built-in/MSO 2021, 14-eh0024TU',
 'Hp Pavilion X360 11Th Gen Intel Core I7 14 Inches Fhd Multitouch 2In1 Laptop (16Gb Ram/512Gb Ssd/B&O/Windows 11 Home/Fpr/Backlit Kb/Intel Iris Xe Graphics/Pen/Alexa/Ms Office/Silver/1.52Kg)14-Dy1047Tu',
 'Lenovo Yoga 7i 11th Gen Intel Core i7-1165G7 14 inches FHD IPS 2-in-1 Touchscreen Business Laptop (16GB/512GB SSD/Windows 10/MS Office/Digital Pen/Fingerprint Reader/Slate Grey/1.43Kg), 82BH004HIN']

In [12]:
#scraping Rating
Rating=[]
rating=driver.find_elements(By.XPATH,'//div[@class="a-row a-size-small"]')

for i in rating[0:10]:
    Rating.append(i.text)
    
Rating

['58', '26', '7', '12', '4', '58', '62', '39', '26', '89']

In [92]:
#scraping Price
Price=[]
price=driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')

for i in price[0:10]:
    Price.append(i.text)
    
Price

['42,999',
 '80,000',
 '74,990',
 '80,000',
 '64,990',
 '77,990',
 '80,990',
 '1,12,950',
 '1,00,000',
 '98,290']